services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: food_recipes
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.40.1  
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/food_recipes
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "your_jwt_secret_key"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - hasura
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/food_recipes
      - HASURA_GRAPHQL_ADMIN_SECRET=myadminsecretkey
    restart: always

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  postgres_data:
